### ISSUE TITLE
Hard Slow

### ISSUE THREAD

**Issue by Joaquimdcp** [airbnb/knowledge-repo#262] opened 2017-05-10 22:46 UTC
Hi my Knowledge is hard slow!

I use it in my local server, with only two posts. And It's very very slow.

Please, anyone cal cap me?
Thank you
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment] 2017-05-10 23:12
Hi @Joaquimdcp ,

Thanks for reporting this! This is a duplicate of #243, which we're working on resolving. So far, I've been unable to reproduce the slow-down locally, so if you can provide your system configuration in this other thread, that may be helpful.

Thanks again!

**Closed by matthewwardrop** 2017-05-10 23:12 UTC
