### ISSUE TITLE
error when pip install in conda  

### ISSUE THREAD

**Issue by iT-Boyer** [airbnb/knowledge-repo#524] opened 2019-11-14 10:06 UTC
conda env
python 3.7
 ```sh
pip install  --upgrade "knowledge-repo[all]"
```
>>
```
Failed to build knowledge-repo flask-login flask-principal flask-mail sqlalchemy inflection blinker alembic regex Mako
Installing collected packages: regex, dateparser, cooked-input, click, itsdangerous, werkzeug, flask, flask-login, blinker, flask-principal, flask-mail, sqlalchemy, Flask-SQLAlchemy, Mako, python-editor, alembic, Flask-Migrate, gunicorn, inflection, pillow, knowledge-repo
    Running setup.py install for regex ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/admin/anaconda3/envs/qq/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/54/dj483jpn7k5_bfwlglg538vw0000gn/T/pip-install-tb0ohbg4/regex/setup.py'"'"'; __file__='"'"'/private/var/folders/54/dj483jpn7k5_bfwlglg538vw0000gn/T/pip-install-tb0ohbg4/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/54/dj483jpn7k5_bfwlglg538vw0000gn/T/pip-record-acauh54w/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/54/dj483jpn7k5_bfwlglg538vw0000gn/T/pip-install-tb0ohbg4/regex/
    Complete output (50 lines):
    running install
    running build
...
```

**Comment by bulam** [comment] 2020-05-27 05:40
Sorry about the delay. Are you still running into this issue? Have you tried installing with a different virtual env?

**Comment by naoyak** [comment] 2020-05-27 05:45
@bulam I just ran into this too. Assuming this is on Mac OS the problem is that the [regex package](https://pypi.org/project/regex/) doesn't have Mac wheels available for all Python versions. We can probably track down the dependency somehow, but one option is to install `regex` through conda.

**Comment by bulam** [comment] 2020-05-27 06:06
Thanks for this solution @naoyak ! Let us know if this works for you @iT-Boyer I'm going to close this issue, but feel free to reopen if this doesn't resolve the error.

**Closed by bulam** 2020-05-27 06:06 UTC
