### ISSUE TITLE
Adding a long commit message

### ISSUE THREAD

**Issue by kaelhuerta** [airbnb/knowledge-repo#115] opened 2016-11-04 05:24 UTC
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hey, reviewers! I'm gathering several questions that I had while testing the repo out. Please let me know if you prefer an issue for each of them.

1. Is there a way of adding a long message to the commits instead of the default `commit -m` style?

2. Why are so many pages displayed even if I have only 2 posts?

![image](https://cloud.githubusercontent.com/assets/6402208/20034810/5bed7006-a391-11e6-977c-8c4a39df9779.png)

3. How do I change the logo? Actually, is not appearing in the server, but when I run the exact same thing locally it does show (the `/static/images/logo-white.svg` one)

4. What are your suggestions in order to change the complete blog theme? Fork this repo and change it?, can it be done with a local config file that I have missed so I always point to the main repository instead of a forked one?

5. My posts are all showing the default thumbnail, how to select which graph to show?

6. Can a button be added (or the one that is there already changed) to toggle the `.Rmd` file instead of the `.md`? This could address #118 in a more elegant way. You write your post hiding all the code for the non-technical readers but allow the curious one to see how it was created by toggling to the raw `.Rmd`

Thanks for the hard work, I'm really enjoying testing it out.
Kael

**Comment by matthewwardrop** [comment] 2016-11-08 18:21
Hi @kaelhuerta,

Thanks for your interest in the knowledge repository :). Let me respond to your questions one by one :).

> Is there a way of adding a long message to the commits instead of the default commit -m style?
At this stage, no. We will be renovating the `GitKnowledgeRepository` class soon, so we'll try to add such support then.

> Why are so many pages displayed even if I have only 2 posts?
The user interface is quite immature, since a lot of recent attention has been spent on improving the back end. The user interface will get incrementally improved over time.

> How do I change the logo? Actually, is not appearing in the server, but when I run the exact same thing locally it does show (the /static/images/logo-white.svg one)
> What are your suggestions in order to change the complete blog theme? Fork this repo and change it?, can it be done with a local config file that I have missed so I always point to the main repository instead of a forked one?
These are probably related. At the moment we don't provide any mechanism for changing the theming of the website. This will come eventually, but we're more interested in fleshing out the functionality before introducing customisation too early into the process (which would just compound our work). Consequently if changing the theming is important to you, short-term, then forking the project is probably your best bet. Regarding the logo, it seems to work as intended here. Can you create a separate issue about that with details of your knowledge_repo and system python versions; as well as which browser you use?

> My posts are all showing the default thumbnail, how to select which graph to show?
Posts use the default thumbnail unless there are images in the post, in which case it uses the first image from the post. Manually specifying the thumbnail is coming soon (see #51).

> Can a button be added (or the one that is there already changed) to toggle the .Rmd file instead of the .md? This could address #118 in a more elegant way. You write your post hiding all the code for the non-technical readers but allow the curious one to see how it was created by toggling to the raw .Rmd
We definitely intend to improve the way in which code is shown, and we intend to make the source files available for download (see #45). Together these should negate the need for an explicit swap between rendered markdown and Rmd.

Hope this helps!

I'm going to close this issue. If I haven't addressed something, or you feel like a specific issue needs more exploration; please feel free to create a new issue with more details :).

**Closed by matthewwardrop** 2016-11-08 18:21 UTC

**Comment by kaelhuerta** [comment] 2016-11-08 18:41
I updated the knowledge repo to the last version and is showing the logo correctly.

But about the thumbnail. Has it to be an image?
If the post has plots, they aren't supposed to show as thumbnail in the current version?

Thanks for the response.

**Comment by matthewwardrop** [comment] 2016-11-08 18:51
Yes. Currently to show up as a thumnbnail, plots must be a static image. [So no plotly instances or anything]. Is that not working for you?

**Comment by kaelhuerta** [comment] 2016-11-08 18:52
No, and it is a ggplot2

**Comment by matthewwardrop** [comment] 2016-11-08 19:38
Hmm... can you send the source code for the generated markdown file? [Appropriately anonymised if necessary]. You can send it directly to my email: matthew <dot> wardrop <at> airbnb.com

**Comment by retroam** [comment] 2016-11-10 16:59
@matthewwardrop was the issue resolved. also experiencing the same issues.

**Comment by matthewwardrop** [comment] 2016-11-10 17:05
@retroam Not yet. Still getting to the bottom of it. Are you also using Rmd files?

**Comment by matthewwardrop** [comment] 2016-11-10 19:54
@retroam @kaelhuerta This is now resolved in #138 . Will be in the next minor release (v0.8.0).

**Comment by retroam** [comment] 2016-11-11 14:44
@matthewwardrop using ipynb
