### ISSUE TITLE
Forced usage of --vanilla breaks our rmarkdown rendering

### ISSUE THREAD

**Issue by bcipolli** [airbnb/knowledge-repo#334] opened 2017-10-14 19:01 UTC
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

We have a local development environment (where we co-develop R packages with analytics scripts) that depends on `.Rprofile` code. This project runs R with `--vanilla`, which skips running this code.

Is there any specific reason this must be done? It strikes me as bad behavior for a package to override default behavior.. by default.

Thank you!

**Comment by danfrankj** [comment] 2017-10-14 19:19
Hi @bcipolli and thanks for your interest in the Knowledge Repository. It seems like we ought to change the R conversion to `R --no-save --no-restore --slave -e`. 

@matthewwardrop  any reason not to do that?

**Comment by matthewwardrop** [comment] 2017-10-17 21:17
@danfrankj Not that I know of. I don't have much experience with R, so I maintained the original code that was written by people who know R better than I do. If there were reasons for it, they've been lost to time.

**Comment by danfrankj** [comment] 2017-10-18 18:50
Hey @bcipolli - Thanks for your interest in KR. This should be fixed via https://github.com/airbnb/knowledge-repo/pull/337 Feel free to reopen if the issue isn't resolved.

**Closed by danfrankj** 2017-10-18 18:50 UTC
Labels: bug
