### ISSUE TITLE
500 errors when accessing knowledge repo through gunicorn deploy

### ISSUE THREAD

**Issue by rcquan** [airbnb/knowledge-repo#25] opened 2016-09-24 06:25 UTC
I am able to successfully use the `runserver` command to start a development server and view the knowledge repo app through my web browser. 

However, when I use the `deploy` command and kick off gunicorn workers successfully, I am unable to load any pages of the knowledge repo in my web browser and instead receive a 500 response.

![image](https://cloud.githubusercontent.com/assets/6497572/18806538/f8c98550-81e4-11e6-8ec9-57c604ea0b9e.png)

Unfortunately, I am unable to provide a useful stack trace since the application logger doesn't seem to print to stdout/stderr when using gunicorn.

**Comment by matthewwardrop** [comment] 2016-09-27 17:13
An update on this: depending on whether you were using multiple repositories via the MetaKnowledgeRepository multiplexer, there were some issues regarding gunicorn deployment that have been fixed in #33 . Can you confirm that you are still having issues @rcquan ?

**Comment by rcquan** [comment] 2016-09-28 07:06
I tried the latest code and ran:
 ```
knowledge_repo --repo <repo_path> --debug deploy
``` 
but am still having the same issues. I am running a single repository. 

The `--debug` flag only gives me a traceback when I run the knowledge repo on a local development server (which works perfectly by the way). When deploying with gunicorn, the Flask logs are not visible in stdout or the browser. They have to be redirected to stderr in order to be picked up by gunicorn (see: https://github.com/airbnb/caravel/pull/335).

**Comment by matthewwardrop** [comment] 2016-09-28 07:21
Hmmm... thanks for following up on this.

The way we currently launch the Gunicorn server leaves a lot to be desired (we create a temporary file, and then run that as a subprocess). We will be tidying this code up in the next couple of days, so I'll wait for a deep dive into this issue until then (especially since I cannot reproduce the bug locally).

It would help at this venture to know your system setup. Are you running this in Linux, Mac OS X or Windows (or something else entirely)? And which version of Python are you using?

If you do get a chance to explore this more yourself, and redirect logging to stderr, I'd love to see some stack traces.

We'll get this sorted one way or another :).

**Closed** 2016-09-28 07:39 UTC

**Comment by matthewwardrop** [comment] 2016-09-28 07:45
@rcquan Oh... wait! This is exactly what should have happened regarding the embedded tooling. The idea is that the embedded tools are frozen at a particular revision, so that all users sharing the repository are using a tested sanctioned version. It also allows you to update the version of the tools used by everyone using your repository without them having to `pip install knowledge-repo` again. You manually update the submodule index in order to update the embedded tools. If you are using it just for yourself, or for a small group of people, you can skip embedding the tools (use --tooling-skip during the `init` phase), or use `--dev` to bypass chaining the `knowledge_repo` command to the embedded version of the tools.

Hope this makes sense.

**Comment by rcquan** [comment] 2016-09-28 09:23
@matthewwardrop Ah, that makes sense! I hadn't realized that the technical details section of the doc also contained information on how to update the knowledge-repo version for the repository. I imagine this will be particularly important point to highlight as y'all bump new versions in the beta ;)
