### ISSUE TITLE
Error when adding an Rmd post

### ISSUE THREAD

**Issue by qthurier** [airbnb/knowledge-repo#47] opened 2016-10-05 21:52 UTC
I got that error when I try to add the Rmd template:

**UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte**

Works fine with the ipynb and md templates.

**Comment by NiharikaRay** [comment] 2016-10-06 01:44
Could you post a snippet of the template (or is this the starter template that we've provided?)

**Comment by qthurier** [comment] 2016-10-06 01:51
Yes it is exactly the Rmd starter template

**Comment by matthewwardrop** [comment] 2016-10-06 07:41
@qthurier We had similar issues internally, but these seemed to be resolved with the most recent version. Just in case, can you confirm the version of the knowledge_repo code you are using is 0.6.3?

I suspect that what may be happening is that you have enabled the embedded tooling and it is using that version rather than your system-installed version. To verify this, try adding the `--dev` option to your command. This enforces using the local version of the knowledge_repo library, rather than that referenced in the repository.

If it still doesn't work, can provide the operating system and python version running on your machine?

**Comment by qthurier** [comment] 2016-10-06 09:20
I'm not sure of the version.. I've installed it today from github following the guide in the README, how can I check the version? Adding --dev doesn't help..
I'm running MacOs El Capitan with Python 3.5.1 | Anaconda 2.4.0

**Comment by earthmancash** [comment] 2016-10-10 19:04
You can check version with the following commands in python shell:

```
import knowledge_repo
knowledge_repo.__version__
```

**Comment by qthurier** [comment] 2016-10-11 01:00
thanks, yes it is '0.6.3'

**Comment by earthmancash** [comment] 2016-10-11 21:36
Interesting, that is the up to date version. We're having some trouble reproducing the issue. What R and knitr version do you have installed? You can get R version with the `version` command, and knitr version with `packageVersion("knitr")`.

**Comment by qthurier** [comment] 2016-10-11 22:37
> version
platform       x86_64-apple-darwin13.4.0
arch           x86_64
os             darwin13.4.0
system         x86_64, darwin13.4.0
status
major          3
minor          3.0
year           2016
month          05
day            03
svn rev        70573
language       R
version.string R version 3.3.0 (2016-05-03)
nickname       Supposedly Educational
> packageVersion("knitr")
[1] ‘1.14’
>

**Comment by matthewwardrop** [comment] 2016-10-12 17:18
Hi @qthurier!

Can you upgrade to 0.6.5 using `pip install --upgrade knowledge-repo`, and then run `knowledge_repo --version`? This will tell us exactly which version of the code is being run when you use the `add` action (the version listed next to `Embedded/active version`). If that turns out to be 0.6.5, then that is very weird; because none of us can reproduce your error locally (and we have very similar versions of the relevant software).

**Comment by qthurier** [comment] 2016-10-13 20:44
Hi @matthewwardrop ,
I've switch to a python 2.7 environment and upgrade to 0.6.6 and Rmd posting works now. Thanks.

**Comment by matthewwardrop** [comment] 2016-10-13 22:31
@qthurier : So Python 3 still fails to work for you? [That would be *very* odd, since in Python 3 UTF-8 encoding is usually a non-issue].

**Comment by matthewwardrop** [comment] 2016-10-14 05:42
This should fixed as of current master. In retrospect, this would have been the same issue as for the Markdown; since only jupyter notebooks skip this stage of the post processing.

**Closed by matthewwardrop** 2016-10-14 05:42 UTC
